CREATE DATABASE IF NOT EXISTS rtrPhotoViewer;

USE rtrPhotoViewer;

CREATE TABLE IF NOT EXISTS photos (
  id INT(3) NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE KEY,
  picOne VARCHAR(12) DEFAULT NULL,
  picTwo VARCHAR(12) DEFAULT NULL,
  picThree VARCHAR(12) DEFAULT NULL,
  picFour VARCHAR(12) DEFAULT NULL );
